using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.CraftCms.DataHandlers.Static;

public class LanguageDataHandler : IStaticDataSourceItemHandler
{
    public IEnumerable<DataSourceItem> GetData()
    {
        return Languages.Select(x => new DataSourceItem(x.Key, x.Value));
    }

    private static Dictionary<string, string> Languages = new()
    {
        { "af", "Afrikaans" },
        { "af-NA", "Afrikaans (Namibia)" },
        { "af-ZA", "Afrikaans (South Africa)" },
        { "agq", "Aghem" },
        { "agq-CM", "Aghem (Cameroon)" },
        { "ak", "Akan" },
        { "ak-GH", "Akan (Ghana)" },
        { "su", "Sundanese" },
        { "su-Latn", "Sundanese (Latin)" },
        { "su-Latn-ID", "Sundanese (Latin, Indonesia)" },
        { "ceb", "Cebuano" },
        { "ceb-PH", "Cebuano (Philippines)" },
        { "kde", "Makonde" },
        { "kde-TZ", "Makonde (Tanzania)" },
        { "cy", "Welsh" },
        { "cy-GB", "Welsh (United Kingdom)" },
        { "de", "German" },
        { "de-BE", "German (Belgium)" },
        { "de-DE", "German (Germany)" },
        { "de-IT", "German (Italy)" },
        { "de-LI", "German (Liechtenstein)" },
        { "de-LU", "German (Luxembourg)" },
        { "de-CH", "German (Switzerland)" },
        { "de-AT", "German (Austria)" },
        { "luo", "Luo" },
        { "luo-KE", "Luo (Kenya)" },
        { "guz", "Gusii" },
        { "guz-KE", "Gusii (Kenya)" },
        { "en", "English" },
        { "en-AS", "English (American Samoa)" },
        { "en-AI", "English (Anguilla)" },
        { "en-AG", "English (Antigua &amp; Barbuda)" },
        { "en-AU", "English (Australia)" },
        { "en-AT", "English (Austria)" },
        { "en-BS", "English (Bahamas)" },
        { "en-BB", "English (Barbados)" },
        { "en-BE", "English (Belgium)" },
        { "en-BZ", "English (Belize)" },
        { "en-BM", "English (Bermuda)" },
        { "en-BW", "English (Botswana)" },
        { "en-IO", "English (British Indian Ocean Territory)" },
        { "en-VG", "English (British Virgin Islands)" },
        { "en-BI", "English (Burundi)" },
        { "en-CM", "English (Cameroon)" },
        { "en-CA", "English (Canada)" },
        { "en-KY", "English (Cayman Islands)" },
        { "en-CX", "English (Christmas Island)" },
        { "en-CC", "English (Cocos [Keeling] Islands)" },
        { "en-CK", "English (Cook Islands)" },
        { "en-CY", "English (Cyprus)" },
        { "en-DK", "English (Denmark)" },
        { "en-DG", "English (Diego Garcia)" },
        { "en-DM", "English (Dominica)" },
        { "en-ER", "English (Eritrea)" },
        { "en-SZ", "English (Eswatini)" },
        { "en-150", "English (Europe)" },
        { "en-FK", "English (Falkland Islands)" },
        { "en-FJ", "English (Fiji)" },
        { "en-FI", "English (Finland)" },
        { "en-GM", "English (Gambia)" },
        { "en-DE", "English (Germany)" },
        { "en-GH", "English (Ghana)" },
        { "en-GI", "English (Gibraltar)" },
        { "en-GD", "English (Grenada)" },
        { "en-GU", "English (Guam)" },
        { "en-GG", "English (Guernsey)" },
        { "en-GY", "English (Guyana)" },
        { "en-HK", "English (Hong Kong SAR China)" },
        { "en-IN", "English (India)" },
        { "en-IE", "English (Ireland)" },
        { "en-IM", "English (Isle of Man)" },
        { "en-IL", "English (Israel)" },
        { "en-JM", "English (Jamaica)" },
        { "en-JE", "English (Jersey)" },
        { "en-KE", "English (Kenya)" },
        { "en-KI", "English (Kiribati)" },
        { "en-LS", "English (Lesotho)" },
        { "en-LR", "English (Liberia)" },
        { "en-MO", "English (Macao SAR China)" },
        { "en-MG", "English (Madagascar)" },
        { "en-MW", "English (Malawi)" },
        { "en-MY", "English (Malaysia)" },
        { "en-MV", "English (Maldives)" },
        { "en-MT", "English (Malta)" },
        { "en-MH", "English (Marshall Islands)" },
        { "en-MU", "English (Mauritius)" },
        { "en-FM", "English (Micronesia)" },
        { "en-MS", "English (Montserrat)" },
        { "en-NA", "English (Namibia)" },
        { "en-NR", "English (Nauru)" },
        { "en-NL", "English (Netherlands)" },
        { "en-NZ", "English (New Zealand)" },
        { "en-NG", "English (Nigeria)" },
        { "en-NU", "English (Niue)" },
        { "en-NF", "English (Norfolk Island)" },
        { "en-MP", "English (Northern Mariana Islands)" },
        { "en-PK", "English (Pakistan)" },
        { "en-PW", "English (Palau)" },
        { "en-PG", "English (Papua New Guinea)" },
        { "en-PH", "English (Philippines)" },
        { "en-PN", "English (Pitcairn Islands)" },
        { "en-PR", "English (Puerto Rico)" },
        { "en-RW", "English (Rwanda)" },
        { "en-WS", "English (Samoa)" },
        { "en-SC", "English (Seychelles)" },
        { "en-SL", "English (Sierra Leone)" },
        { "en-SG", "English (Singapore)" },
        { "en-SX", "English (Sint Maarten)" },
        { "en-SI", "English (Slovenia)" },
        { "en-SB", "English (Solomon Islands)" },
        { "en-ZA", "English (South Africa)" },
        { "en-SS", "English (South Sudan)" },
        { "en-SH", "English (St. Helena)" },
        { "en-KN", "English (St. Kitts &amp; Nevis)" },
        { "en-LC", "English (St. Lucia)" },
        { "en-VC", "English (St. Vincent &amp; Grenadines)" },
        { "en-SD", "English (Sudan)" },
        { "en-SE", "English (Sweden)" },
        { "en-CH", "English (Switzerland)" },
        { "en-TZ", "English (Tanzania)" },
        { "en-TK", "English (Tokelau)" },
        { "en-TO", "English (Tonga)" },
        { "en-TT", "English (Trinidad &amp; Tobago)" },
        { "en-TC", "English (Turks &amp; Caicos Islands)" },
        { "en-TV", "English (Tuvalu)" },
        { "en-UM", "English (U.S. Outlying Islands)" },
        { "en-VI", "English (U.S. Virgin Islands)" },
        { "en-UG", "English (Uganda)" },
        { "en-AE", "English (United Arab Emirates)" },
        { "en-GB", "English (United Kingdom)" },
        { "en-US", "English (United States)" },
        { "en-US-POSIX", "English (United States, Computer)" },
        { "en-VU", "English (Vanuatu)" },
        { "en-ZM", "English (Zambia)" },
        { "en-ZW", "English (Zimbabwe)" },
        { "en-001", "English (world)" },
        { "ee", "Ewe" },
        { "ee-GH", "Ewe (Ghana)" },
        { "ee-TG", "Ewe (Togo)" },
        { "fil", "Filipino" },
        { "fil-PH", "Filipino (Philippines)" },
        { "fy", "Western Frisian" },
        { "fy-NL", "Western Frisian (Netherlands)" },
        { "ga", "Irish" },
        { "ga-GB", "Irish (United Kingdom)" },
        { "ga-IE", "Irish (Ireland)" },
        { "gv", "Manx" },
        { "gv-IM", "Manx (Isle of Man)" },
        { "ki", "Kikuyu" },
        { "ki-KE", "Kikuyu (Kenya)" },
        { "gd", "Scottish Gaelic" },
        { "gd-GB", "Scottish Gaelic (United Kingdom)" },
        { "ha", "Hausa" },
        { "ha-GH", "Hausa (Ghana)" },
        { "ha-NE", "Hausa (Niger)" },
        { "ha-NG", "Hausa (Nigeria)" },
        { "bez", "Bena" },
        { "bez-TZ", "Bena (Tanzania)" },
        { "hi-Latn", "Hindi (Latin)" },
        { "hi-Latn-IN", "Hindi (Latin, India)" },
        { "bem", "Bemba" },
        { "bem-ZM", "Bemba (Zambia)" },
        { "ig", "Igbo" },
        { "ig-NG", "Igbo (Nigeria)" },
        { "rn", "Rundi" },
        { "rn-BI", "Rundi (Burundi)" },
        { "id", "Indonesian" },
        { "id-ID", "Indonesian (Indonesia)" },
        { "sbp", "Sangu" },
        { "sbp-TZ", "Sangu (Tanzania)" },
        { "xh", "Xhosa" },
        { "xh-ZA", "Xhosa (South Africa)" },
        { "jv", "Javanese" },
        { "jv-ID", "Javanese (Indonesia)" },
        { "kln", "Kalenjin" },
        { "kln-KE", "Kalenjin (Kenya)" },
        { "naq", "Nama" },
        { "naq-NA", "Nama (Namibia)" },
        { "rof", "Rombo" },
        { "rof-TZ", "Rombo (Tanzania)" },
        { "kam", "Kamba" },
        { "kam-KE", "Kamba (Kenya)" },
        { "jmc", "Machame" },
        { "jmc-TZ", "Machame (Tanzania)" },
        { "rw", "Kinyarwanda" },
        { "rw-RW", "Kinyarwanda (Rwanda)" },
        { "asa", "Asu" },
        { "asa-TZ", "Asu (Tanzania)" },
        { "rwk", "Rwa" },
        { "rwk-TZ", "Rwa (Tanzania)" },
        { "saq", "Samburu" },
        { "saq-KE", "Samburu (Kenya)" },
        { "ksb", "Shambala" },
        { "ksb-TZ", "Shambala (Tanzania)" },
        { "sw", "Swahili" },
        { "sw-CD", "Swahili (Congo - Kinshasa)" },
        { "sw-KE", "Swahili (Kenya)" },
        { "sw-TZ", "Swahili (Tanzania)" },
        { "sw-UG", "Swahili (Uganda)" },
        { "dav", "Taita" },
        { "dav-KE", "Taita (Kenya)" },
        { "teo", "Teso" },
        { "teo-KE", "Teso (Kenya)" },
        { "teo-UG", "Teso (Uganda)" },
        { "khq", "Koyra Chiini" },
        { "khq-ML", "Koyra Chiini (Mali)" },
        { "ses", "Koyraboro Senni" },
        { "ses-ML", "Koyraboro Senni (Mali)" },
        { "vun", "Vunjo" },
        { "vun-TZ", "Vunjo (Tanzania)" },
        { "ksh", "Colognian" },
        { "ksh-DE", "Colognian (Germany)" },
        { "ebu", "Embu" },
        { "ebu-KE", "Embu (Kenya)" },
        { "mer", "Meru" },
        { "mer-KE", "Meru (Kenya)" },
        { "lag", "Langi" },
        { "lag-TZ", "Langi (Tanzania)" },
        { "lkt", "Lakota" },
        { "lkt-US", "Lakota (United States)" },
        { "lg", "Ganda" },
        { "lg-UG", "Ganda (Uganda)" },
        { "luy", "Luyia" },
        { "luy-KE", "Luyia (Kenya)" },
        { "lb", "Luxembourgish" },
        { "lb-LU", "Luxembourgish (Luxembourg)" },
        { "mua", "Mundang" },
        { "mua-CM", "Mundang (Cameroon)" },
        { "mas", "Masai" },
        { "mas-KE", "Masai (Kenya)" },
        { "mas-TZ", "Masai (Tanzania)" },
        { "mgh", "Makhuwa-Meetto" },
        { "mgh-MZ", "Makhuwa-Meetto (Mozambique)" },
        { "mg", "Malagasy" },
        { "mg-MG", "Malagasy (Madagascar)" },
        { "mt", "Maltese" },
        { "mt-MT", "Maltese (Malta)" },
        { "ms", "Malay" },
        { "ms-BN", "Malay (Brunei)" },
        { "ms-ID", "Malay (Indonesia)" },
        { "ms-MY", "Malay (Malaysia)" },
        { "ms-SG", "Malay (Singapore)" },
        { "mi", "Māori" },
        { "mi-NZ", "Māori (New Zealand)" },
        { "pcm", "Nigerian Pidgin" },
        { "pcm-NG", "Nigerian Pidgin (Nigeria)" },
        { "jgo", "Ngomba" },
        { "jgo-CM", "Ngomba (Cameroon)" },
        { "nl", "Dutch" },
        { "nl-AW", "Dutch (Aruba)" },
        { "nl-BE", "Dutch (Belgium)" },
        { "nl-BQ", "Dutch (Caribbean Netherlands)" },
        { "nl-CW", "Dutch (Curaçao)" },
        { "nl-NL", "Dutch (Netherlands)" },
        { "nl-SX", "Dutch (Sint Maarten)" },
        { "nl-SR", "Dutch (Suriname)" },
        { "xog", "Soga" },
        { "xog-UG", "Soga (Uganda)" },
        { "om", "Oromo" },
        { "om-ET", "Oromo (Ethiopia)" },
        { "om-KE", "Oromo (Kenya)" },
        { "ff", "Fula" },
        { "ff-Latn", "Fula (Latin)" },
        { "ff-Latn-BF", "Fula (Latin, Burkina Faso)" },
        { "ff-Latn-GM", "Fula (Latin, Gambia)" },
        { "ff-Latn-GH", "Fula (Latin, Ghana)" },
        { "ff-Latn-GN", "Fula (Latin, Guinea)" },
        { "ff-Latn-GW", "Fula (Latin, Guinea-Bissau)" },
        { "ff-Latn-CM", "Fula (Latin, Cameroon)" },
        { "ff-Latn-LR", "Fula (Latin, Liberia)" },
        { "ff-Latn-MR", "Fula (Latin, Mauritania)" },
        { "ff-Latn-NE", "Fula (Latin, Niger)" },
        { "ff-Latn-NG", "Fula (Latin, Nigeria)" },
        { "ff-Latn-SN", "Fula (Latin, Senegal)" },
        { "ff-Latn-SL", "Fula (Latin, Sierra Leone)" },
        { "cgg", "Chiga" },
        { "cgg-UG", "Chiga (Uganda)" },
        { "qu", "Quechua" },
        { "qu-BO", "Quechua (Bolivia)" },
        { "qu-EC", "Quechua (Ecuador)" },
        { "qu-PE", "Quechua (Peru)" },
        { "nyn", "Nyankole" },
        { "nyn-UG", "Nyankole (Uganda)" },
        { "gsw", "Swiss German" },
        { "gsw-FR", "Swiss German (France)" },
        { "gsw-LI", "Swiss German (Liechtenstein)" },
        { "gsw-CH", "Swiss German (Switzerland)" },
        { "nnh", "Ngiemboon" },
        { "nnh-CM", "Ngiemboon (Cameroon)" },
        { "so", "Somali" },
        { "so-ET", "Somali (Ethiopia)" },
        { "so-DJ", "Somali (Djibouti)" },
        { "so-KE", "Somali (Kenya)" },
        { "so-SO", "Somali (Somalia)" },
        { "sg", "Sango" },
        { "sg-CF", "Sango (Central African Republic)" },
        { "tzm", "Central Atlas Tamazight" },
        { "tzm-MA", "Central Atlas Tamazight (Morocco)" },
        { "kab", "Kabyle" },
        { "kab-DZ", "Kabyle (Algeria)" },
        { "twq", "Tasawaq" },
        { "twq-NE", "Tasawaq (Niger)" },
        { "shi-Latn", "Tachelhit (Latin)" },
        { "shi-Latn-MA", "Tachelhit (Latin, Morocco)" },
        { "nus", "Nuer" },
        { "nus-SS", "Nuer (South Sudan)" },
        { "vi", "Vietnamese" },
        { "vi-VN", "Vietnamese (Vietnam)" },
        { "lu", "Luba-Katanga" },
        { "lu-CD", "Luba-Katanga (Congo - Kinshasa)" },
        { "tr", "Turkish" },
        { "tr-CY", "Turkish (Cyprus)" },
        { "tr-TR", "Turkish (Turkey)" },
        { "vai-Latn", "Vai (Latin)" },
        { "vai-Latn-LR", "Vai (Latin, Liberia)" },
        { "wae", "Walser" },
        { "wae-CH", "Walser (Switzerland)" },
        { "wo", "Wolof" },
        { "wo-SN", "Wolof (Senegal)" },
        { "dje", "Zarma" },
        { "dje-NE", "Zarma (Niger)" },
        { "smn", "Inari Sami" },
        { "smn-FI", "Inari Sami (Finland)" },
        { "ast", "Asturian" },
        { "ast-ES", "Asturian (Spain)" },
        { "az", "Azerbaijani" },
        { "az-Latn", "Azerbaijani (Latin)" },
        { "az-Latn-AZ", "Azerbaijani (Latin, Azerbaijan)" },
        { "bm", "Bambara" },
        { "bm-ML", "Bambara (Mali)" },
        { "bs", "Bosnian" },
        { "bs-Latn", "Bosnian (Latin)" },
        { "bs-Latn-BA", "Bosnian (Latin, Bosnia &amp; Herzegovina)" },
        { "br", "Breton" },
        { "br-FR", "Breton (France)" },
        { "ca", "Catalan" },
        { "ca-AD", "Catalan (Andorra)" },
        { "ca-ES", "Catalan (Spain)" },
        { "ca-FR", "Catalan (France)" },
        { "ca-IT", "Catalan (Italy)" },
        { "sn", "Shona" },
        { "sn-ZW", "Shona (Zimbabwe)" },
        { "da", "Danish" },
        { "da-DK", "Danish (Denmark)" },
        { "da-GL", "Danish (Greenland)" },
        { "se", "Northern Sami" },
        { "se-NO", "Northern Sami (Norway)" },
        { "se-SE", "Northern Sami (Sweden)" },
        { "se-FI", "Northern Sami (Finland)" },
        { "dsb", "Lower Sorbian" },
        { "dsb-DE", "Lower Sorbian (Germany)" },
        { "dua", "Duala" },
        { "dua-CM", "Duala (Cameroon)" },
        { "et", "Estonian" },
        { "et-EE", "Estonian (Estonia)" },
        { "es", "Spanish" },
        { "es-AR", "Spanish (Argentina)" },
        { "es-BZ", "Spanish (Belize)" },
        { "es-BO", "Spanish (Bolivia)" },
        { "es-BR", "Spanish (Brazil)" },
        { "es-IC", "Spanish (Canary Islands)" },
        { "es-EA", "Spanish (Ceuta &amp; Melilla)" },
        { "es-CL", "Spanish (Chile)" },
        { "es-CO", "Spanish (Colombia)" },
        { "es-CR", "Spanish (Costa Rica)" },
        { "es-CU", "Spanish (Cuba)" },
        { "es-EC", "Spanish (Ecuador)" },
        { "es-SV", "Spanish (El Salvador)" },
        { "es-ES", "Spanish (Spain)" },
        { "es-US", "Spanish (United States)" },
        { "es-PH", "Spanish (Philippines)" },
        { "es-GT", "Spanish (Guatemala)" },
        { "es-GQ", "Spanish (Equatorial Guinea)" },
        { "es-HN", "Spanish (Honduras)" },
        { "es-419", "Spanish (Latin America)" },
        { "es-MX", "Spanish (Mexico)" },
        { "es-NI", "Spanish (Nicaragua)" },
        { "es-PA", "Spanish (Panama)" },
        { "es-PY", "Spanish (Paraguay)" },
        { "es-PE", "Spanish (Peru)" },
        { "es-PR", "Spanish (Puerto Rico)" },
        { "es-DO", "Spanish (Dominican Republic)" },
        { "es-UY", "Spanish (Uruguay)" },
        { "es-VE", "Spanish (Venezuela)" },
        { "eo", "Esperanto" },
        { "eo-001", "Esperanto (world)" },
        { "eu", "Basque" },
        { "eu-ES", "Basque (Spain)" },
        { "ewo", "Ewondo" },
        { "ewo-CM", "Ewondo (Cameroon)" },
        { "fr", "French" },
        { "fr-DZ", "French (Algeria)" },
        { "fr-BE", "French (Belgium)" },
        { "fr-BF", "French (Burkina Faso)" },
        { "fr-BI", "French (Burundi)" },
        { "fr-BJ", "French (Benin)" },
        { "fr-CM", "French (Cameroon)" },
        { "fr-CA", "French (Canada)" },
        { "fr-KM", "French (Comoros)" },
        { "fr-CG", "French (Congo - Brazzaville)" },
        { "fr-CD", "French (Congo - Kinshasa)" },
        { "fr-CI", "French (Côte d’Ivoire)" },
        { "fr-DJ", "French (Djibouti)" },
        { "fr-FR", "French (France)" },
        { "fr-GA", "French (Gabon)" },
        { "fr-GP", "French (Guadeloupe)" },
        { "fr-GQ", "French (Equatorial Guinea)" },
        { "fr-GN", "French (Guinea)" },
        { "fr-GF", "French (French Guiana)" },
        { "fr-HT", "French (Haiti)" },
        { "fr-RE", "French (Réunion)" },
        { "fr-LU", "French (Luxembourg)" },
        { "fr-MG", "French (Madagascar)" },
        { "fr-ML", "French (Mali)" },
        { "fr-MA", "French (Morocco)" },
        { "fr-MQ", "French (Martinique)" },
        { "fr-MU", "French (Mauritius)" },
        { "fr-MR", "French (Mauritania)" },
        { "fr-YT", "French (Mayotte)" },
        { "fr-MC", "French (Monaco)" },
        { "fr-NE", "French (Niger)" },
        { "fr-NC", "French (New Caledonia)" },
        { "fr-PF", "French (French Polynesia)" },
        { "fr-RW", "French (Rwanda)" },
        { "fr-CF", "French (Central African Republic)" },
        { "fr-BL", "French (St. Barthélemy)" },
        { "fr-MF", "French (St. Martin)" },
        { "fr-PM", "French (St. Pierre &amp; Miquelon)" },
        { "fr-SC", "French (Seychelles)" },
        { "fr-CH", "French (Switzerland)" },
        { "fr-SY", "French (Syria)" },
        { "fr-SN", "French (Senegal)" },
        { "fr-TD", "French (Chad)" },
        { "fr-TG", "French (Togo)" },
        { "fr-TN", "French (Tunisia)" },
        { "fr-VU", "French (Vanuatu)" },
        { "fr-WF", "French (Wallis &amp; Futuna)" },
        { "fur", "Friulian" },
        { "fur-IT", "Friulian (Italy)" },
        { "fo", "Faroese" },
        { "fo-DK", "Faroese (Denmark)" },
        { "fo-FO", "Faroese (Faroe Islands)" },
        { "gl", "Galician" },
        { "gl-ES", "Galician (Spain)" },
        { "hsb", "Upper Sorbian" },
        { "hsb-DE", "Upper Sorbian (Germany)" },
        { "hr", "Croatian" },
        { "hr-BA", "Croatian (Bosnia &amp; Herzegovina)" },
        { "hr-HR", "Croatian (Croatia)" },
        { "ia", "Interlingua" },
        { "ia-001", "Interlingua (world)" },
        { "nd", "North Ndebele" },
        { "nd-ZW", "North Ndebele (Zimbabwe)" },
        { "zu", "Zulu" },
        { "zu-ZA", "Zulu (South Africa)" },
        { "it", "Italian" },
        { "it-VA", "Italian (Vatican City)" },
        { "it-IT", "Italian (Italy)" },
        { "it-SM", "Italian (San Marino)" },
        { "it-CH", "Italian (Switzerland)" },
        { "dyo", "Jola-Fonyi" },
        { "dyo-SN", "Jola-Fonyi (Senegal)" },
        { "kea", "Kabuverdianu" },
        { "kea-CV", "Kabuverdianu (Cape Verde)" },
        { "kkj", "Kako" },
        { "kkj-CM", "Kako (Cameroon)" },
        { "kl", "Kalaallisut" },
        { "kl-GL", "Kalaallisut (Greenland)" },
        { "kgp", "Kaingang" },
        { "kgp-BR", "Kaingang (Brazil)" },
        { "kw", "Cornish" },
        { "kw-GB", "Cornish (United Kingdom)" },
        { "mfe", "Morisyen" },
        { "mfe-MU", "Morisyen (Mauritius)" },
        { "ku", "Kurdish" },
        { "ku-TR", "Kurdish (Turkey)" },
        { "lv", "Latvian" },
        { "lv-LV", "Latvian (Latvia)" },
        { "to", "Tongan" },
        { "to-TO", "Tongan (Tonga)" },
        { "lt", "Lithuanian" },
        { "lt-LT", "Lithuanian (Lithuania)" },
        { "ln", "Lingala" },
        { "ln-AO", "Lingala (Angola)" },
        { "ln-CG", "Lingala (Congo - Brazzaville)" },
        { "ln-CF", "Lingala (Central African Republic)" },
        { "ln-CD", "Lingala (Congo - Kinshasa)" },
        { "hu", "Hungarian" },
        { "hu-HU", "Hungarian (Hungary)" },
        { "mgo", "Metaʼ" },
        { "mgo-CM", "Metaʼ (Cameroon)" },
        { "yrl", "Nheengatu" },
        { "yrl-BR", "Nheengatu (Brazil)" },
        { "nmg", "Kwasio" },
        { "nmg-CM", "Kwasio (Cameroon)" },
        { "no", "Norwegian" },
        { "nb", "Norwegian Bokmål" },
        { "nb-NO", "Norwegian Bokmål (Norway)" },
        { "nb-SJ", "Norwegian Bokmål (Svalbard &amp; Jan Mayen)" },
        { "nn", "Norwegian Nynorsk" },
        { "nn-NO", "Norwegian Nynorsk (Norway)" },
        { "yav", "Yangben" },
        { "yav-CM", "Yangben (Cameroon)" },
        { "uz", "Uzbek" },
        { "uz-Latn", "Uzbek (Latin)" },
        { "uz-Latn-UZ", "Uzbek (Latin, Uzbekistan)" },
        { "pl", "Polish" },
        { "pl-PL", "Polish (Poland)" },
        { "pt", "Portuguese" },
        { "pt-AO", "Portuguese (Angola)" },
        { "pt-BR", "Portuguese (Brazil)" },
        { "pt-CV", "Portuguese (Cape Verde)" },
        { "pt-GQ", "Portuguese (Equatorial Guinea)" },
        { "pt-GW", "Portuguese (Guinea-Bissau)" },
        { "pt-LU", "Portuguese (Luxembourg)" },
        { "pt-MO", "Portuguese (Macao SAR China)" },
        { "pt-MZ", "Portuguese (Mozambique)" },
        { "pt-PT", "Portuguese (Portugal)" },
        { "pt-CH", "Portuguese (Switzerland)" },
        { "pt-ST", "Portuguese (São Tomé &amp; Príncipe)" },
        { "pt-TL", "Portuguese (Timor-Leste)" },
        { "ksf", "Bafia" },
        { "ksf-CM", "Bafia (Cameroon)" },
        { "ro", "Romanian" },
        { "ro-MD", "Romanian (Moldova)" },
        { "ro-RO", "Romanian (Romania)" },
        { "rm", "Romansh" },
        { "rm-CH", "Romansh (Switzerland)" },
        { "sc", "Sardinian" },
        { "sc-IT", "Sardinian (Italy)" },
        { "seh", "Sena" },
        { "seh-MZ", "Sena (Mozambique)" },
        { "sq", "Albanian" },
        { "sq-XK", "Albanian (Kosovo)" },
        { "sq-MK", "Albanian (North Macedonia)" },
        { "sq-AL", "Albanian (Albania)" },
        { "sk", "Slovak" },
        { "sk-SK", "Slovak (Slovakia)" },
        { "sl", "Slovenian" },
        { "sl-SI", "Slovenian (Slovenia)" },
        { "sr-Latn", "Serbian (Latin)" },
        { "sr-Latn-BA", "Serbian (Latin, Bosnia &amp; Herzegovina)" },
        { "sr-Latn-ME", "Serbian (Latin, Montenegro)" },
        { "sr-Latn-XK", "Serbian (Latin, Kosovo)" },
        { "sr-Latn-RS", "Serbian (Latin, Serbia)" },
        { "fi", "Finnish" },
        { "fi-FI", "Finnish (Finland)" },
        { "sv", "Swedish" },
        { "sv-FI", "Swedish (Finland)" },
        { "sv-SE", "Swedish (Sweden)" },
        { "sv-AX", "Swedish (Åland Islands)" },
        { "tk", "Turkmen" },
        { "tk-TM", "Turkmen (Turkmenistan)" },
        { "yo", "Yoruba" },
        { "yo-BJ", "Yoruba (Benin)" },
        { "yo-NG", "Yoruba (Nigeria)" },
        { "is", "Icelandic" },
        { "is-IS", "Icelandic (Iceland)" },
        { "yrl-CO", "Nheengatu (Colombia)" },
        { "yrl-VE", "Nheengatu (Venezuela)" },
        { "cs", "Czech" },
        { "cs-CZ", "Czech (Czechia)" },
        { "bas", "Basaa" },
        { "bas-CM", "Basaa (Cameroon)" },
        { "haw", "Hawaiian" },
        { "haw-US", "Hawaiian (United States)" },
        { "el", "Greek" },
        { "el-GR", "Greek (Greece)" },
        { "el-CY", "Greek (Cyprus)" },
        { "az-Cyrl", "Azerbaijani (Cyrillic)" },
        { "az-Cyrl-AZ", "Azerbaijani (Cyrillic, Azerbaijan)" },
        { "be", "Belarusian" },
        { "be-BY", "Belarusian (Belarus)" },
        { "bs-Cyrl", "Bosnian (Cyrillic)" },
        { "bs-Cyrl-BA", "Bosnian (Cyrillic, Bosnia &amp; Herzegovina)" },
        { "bg", "Bulgarian" },
        { "bg-BG", "Bulgarian (Bulgaria)" },
        { "os", "Ossetic" },
        { "os-GE", "Ossetic (Georgia)" },
        { "os-RU", "Ossetic (Russia)" },
        { "ky", "Kyrgyz" },
        { "ky-KG", "Kyrgyz (Kyrgyzstan)" },
        { "mk", "Macedonian" },
        { "mk-MK", "Macedonian (North Macedonia)" },
        { "mn", "Mongolian" },
        { "mn-MN", "Mongolian (Mongolia)" },
        { "ce", "Chechen" },
        { "ce-RU", "Chechen (Russia)" },
        { "ru", "Russian" },
        { "ru-BY", "Russian (Belarus)" },
        { "ru-KZ", "Russian (Kazakhstan)" },
        { "ru-KG", "Russian (Kyrgyzstan)" },
        { "ru-MD", "Russian (Moldova)" },
        { "ru-RU", "Russian (Russia)" },
        { "ru-UA", "Russian (Ukraine)" },
        { "sah", "Yakut" },
        { "sah-RU", "Yakut (Russia)" },
        { "sr", "Serbian" },
        { "sr-Cyrl", "Serbian (Cyrillic)" },
        { "sr-Cyrl-BA", "Serbian (Cyrillic, Bosnia &amp; Herzegovina)" },
        { "sr-Cyrl-XK", "Serbian (Cyrillic, Kosovo)" },
        { "sr-Cyrl-RS", "Serbian (Cyrillic, Serbia)" },
        { "sr-Cyrl-ME", "Serbian (Cyrillic, Montenegro)" },
        { "tt", "Tatar" },
        { "tt-RU", "Tatar (Russia)" },
        { "tg", "Tajik" },
        { "tg-TJ", "Tajik (Tajikistan)" },
        { "uk", "Ukrainian" },
        { "uk-UA", "Ukrainian (Ukraine)" },
        { "cv", "Chuvash" },
        { "cv-RU", "Chuvash (Russia)" },
        { "uz-Cyrl", "Uzbek (Cyrillic)" },
        { "uz-Cyrl-UZ", "Uzbek (Cyrillic, Uzbekistan)" },
        { "kk", "Kazakh" },
        { "kk-KZ", "Kazakh (Kazakhstan)" },
        { "hy", "Armenian" },
        { "hy-AM", "Armenian (Armenia)" },
        { "yi", "Yiddish" },
        { "yi-001", "Yiddish (world)" },
        { "he", "Hebrew" },
        { "he-IL", "Hebrew (Israel)" },
        { "ug", "Uyghur" },
        { "ug-CN", "Uyghur (China)" },
        { "ur", "Urdu" },
        { "ur-IN", "Urdu (India)" },
        { "ur-PK", "Urdu (Pakistan)" },
        { "ar", "Arabic" },
        { "ar-ER", "Arabic (Eritrea)" },
        { "ar-IL", "Arabic (Israel)" },
        { "ar-PS", "Arabic (Palestinian Territories)" },
        { "ar-JO", "Arabic (Jordan)" },
        { "ar-AE", "Arabic (United Arab Emirates)" },
        { "ar-BH", "Arabic (Bahrain)" },
        { "ar-DZ", "Arabic (Algeria)" },
        { "ar-SD", "Arabic (Sudan)" },
        { "ar-EH", "Arabic (Western Sahara)" },
        { "ar-SO", "Arabic (Somalia)" },
        { "ar-001", "Arabic (world)" },
        { "ar-IQ", "Arabic (Iraq)" },
        { "ar-KW", "Arabic (Kuwait)" },
        { "ar-MA", "Arabic (Morocco)" },
        { "ar-SA", "Arabic (Saudi Arabia)" },
        { "ar-YE", "Arabic (Yemen)" },
        { "ar-TD", "Arabic (Chad)" },
        { "ar-TN", "Arabic (Tunisia)" },
        { "ar-KM", "Arabic (Comoros)" },
        { "ar-SS", "Arabic (South Sudan)" },
        { "ar-DJ", "Arabic (Djibouti)" },
        { "ar-SY", "Arabic (Syria)" },
        { "ar-OM", "Arabic (Oman)" },
        { "ar-QA", "Arabic (Qatar)" },
        { "ar-LB", "Arabic (Lebanon)" },
        { "ar-LY", "Arabic (Libya)" },
        { "ar-EG", "Arabic (Egypt)" },
        { "ar-MR", "Arabic (Mauritania)" },
        { "uz-Arab", "Uzbek (Arabic)" },
        { "uz-Arab-AF", "Uzbek (Arabic, Afghanistan)" },
        { "sd", "Sindhi" },
        { "sd-Arab", "Sindhi (Arabic)" },
        { "sd-Arab-PK", "Sindhi (Arabic, Pakistan)" },
        { "fa", "Persian" },
        { "fa-AF", "Persian (Afghanistan)" },
        { "fa-IR", "Persian (Iran)" },
        { "lrc", "Northern Luri" },
        { "lrc-IQ", "Northern Luri (Iraq)" },
        { "lrc-IR", "Northern Luri (Iran)" },
        { "mzn", "Mazanderani" },
        { "mzn-IR", "Mazanderani (Iran)" },
        { "pa-Arab", "Punjabi (Arabic)" },
        { "pa-Arab-PK", "Punjabi (Arabic, Pakistan)" },
        { "ps", "Pashto" },
        { "ps-AF", "Pashto (Afghanistan)" },
        { "ps-PK", "Pashto (Pakistan)" },
        { "ckb", "Central Kurdish" },
        { "ckb-IR", "Central Kurdish (Iran)" },
        { "ckb-IQ", "Central Kurdish (Iraq)" },
        { "ks", "Kashmiri" },
        { "ks-Arab", "Kashmiri (Arabic)" },
        { "ks-Arab-IN", "Kashmiri (Arabic, India)" },
        { "ks-Deva", "Kashmiri (Devanagari)" },
        { "ks-Deva-IN", "Kashmiri (Devanagari, India)" },
        { "kok", "Konkani" },
        { "kok-IN", "Konkani (India)" },
        { "doi", "Dogri" },
        { "doi-IN", "Dogri (India)" },
        { "ne", "Nepali" },
        { "ne-NP", "Nepali (Nepal)" },
        { "ne-IN", "Nepali (India)" },
        { "brx", "Bodo" },
        { "brx-IN", "Bodo (India)" },
        { "bho", "Bhojpuri" },
        { "bho-IN", "Bhojpuri (India)" },
        { "mr", "Marathi" },
        { "mr-IN", "Marathi (India)" },
        { "mai", "Maithili" },
        { "mai-IN", "Maithili (India)" },
        { "raj", "Rajasthani" },
        { "raj-IN", "Rajasthani (India)" },
        { "sa", "Sanskrit" },
        { "sa-IN", "Sanskrit (India)" },
        { "sd-Deva", "Sindhi (Devanagari)" },
        { "sd-Deva-IN", "Sindhi (Devanagari, India)" },
        { "bgc", "Haryanvi" },
        { "bgc-IN", "Haryanvi (India)" },
        { "hi", "Hindi" },
        { "hi-IN", "Hindi (India)" },
        { "as", "Assamese" },
        { "as-IN", "Assamese (India)" },
        { "bn", "Bangla" },
        { "bn-BD", "Bangla (Bangladesh)" },
        { "bn-IN", "Bangla (India)" },
        { "mni", "Manipuri" },
        { "mni-Beng", "Manipuri (Bangla)" },
        { "mni-Beng-IN", "Manipuri (Bangla, India)" },
        { "pa", "Punjabi" },
        { "pa-Guru", "Punjabi (Gurmukhi)" },
        { "pa-Guru-IN", "Punjabi (Gurmukhi, India)" },
        { "gu", "Gujarati" },
        { "gu-IN", "Gujarati (India)" },
        { "or", "Odia" },
        { "or-IN", "Odia (India)" },
        { "ta", "Tamil" },
        { "ta-IN", "Tamil (India)" },
        { "ta-LK", "Tamil (Sri Lanka)" },
        { "ta-SG", "Tamil (Singapore)" },
        { "ta-MY", "Tamil (Malaysia)" },
        { "te", "Telugu" },
        { "te-IN", "Telugu (India)" },
        { "kn", "Kannada" },
        { "kn-IN", "Kannada (India)" },
        { "ml", "Malayalam" },
        { "ml-IN", "Malayalam (India)" },
        { "si", "Sinhala" },
        { "si-LK", "Sinhala (Sri Lanka)" },
        { "th", "Thai" },
        { "th-TH", "Thai (Thailand)" },
        { "lo", "Lao" },
        { "lo-LA", "Lao (Laos)" },
        { "bo", "Tibetan" },
        { "bo-IN", "Tibetan (India)" },
        { "bo-CN", "Tibetan (China)" },
        { "dz", "Dzongkha" },
        { "dz-BT", "Dzongkha (Bhutan)" },
        { "my", "Burmese" },
        { "my-MM", "Burmese (Myanmar [Burma])" },
        { "ka", "Georgian" },
        { "ka-GE", "Georgian (Georgia)" },
        { "ti", "Tigrinya" },
        { "ti-ET", "Tigrinya (Ethiopia)" },
        { "ti-ER", "Tigrinya (Eritrea)" },
        { "am", "Amharic" },
        { "am-ET", "Amharic (Ethiopia)" },
        { "chr", "Cherokee" },
        { "chr-US", "Cherokee (United States)" },
        { "km", "Khmer" },
        { "km-KH", "Khmer (Cambodia)" },
        { "sat", "Santali" },
        { "sat-Olck", "Santali (Ol Chiki)" },
        { "sat-Olck-IN", "Santali (Ol Chiki, India)" },
        { "zgh", "Standard Moroccan Tamazight" },
        { "zgh-MA", "Standard Moroccan Tamazight (Morocco)" },
        { "shi", "Tachelhit" },
        { "shi-Tfng", "Tachelhit (Tifinagh)" },
        { "shi-Tfng-MA", "Tachelhit (Tifinagh, Morocco)" },
        { "zh", "Chinese" },
        { "zh-Hans", "Chinese (Simplified)" },
        { "zh-Hans-MO", "Chinese (Simplified, Macao SAR China)" },
        { "zh-Hans-HK", "Chinese (Simplified, Hong Kong SAR China)" },
        { "zh-Hans-CN", "Chinese (Simplified, China)" },
        { "zh-Hans-SG", "Chinese (Simplified, Singapore)" },
        { "zh-Hant-MO", "Chinese (Traditional, Macao SAR China)" },
        { "zh-Hant-HK", "Chinese (Traditional, Hong Kong SAR China)" },
        { "zh-Hant", "Chinese (Traditional)" },
        { "zh-Hant-TW", "Chinese (Traditional, Taiwan)" },
        { "ja", "Japanese" },
        { "ja-JP", "Japanese (Japan)" },
        { "yue-Hans", "Cantonese (Simplified)" },
        { "yue-Hans-CN", "Cantonese (Simplified, China)" },
        { "yue", "Cantonese" },
        { "yue-Hant", "Cantonese (Traditional)" },
        { "yue-Hant-HK", "Cantonese (Traditional, Hong Kong SAR China)" },
        { "ii", "Sichuan Yi" },
        { "ii-CN", "Sichuan Yi (China)" },
        { "vai", "Vai" },
        { "vai-Vaii", "Vai (Vai)" },
        { "vai-Vaii-LR", "Vai (Vai, Liberia)" },
        { "ko", "Korean" },
        { "ko-KR", "Korean (South Korea)" },
        { "ko-KP", "Korean (North Korea)" },
        { "ccp", "Chakma" },
        { "ccp-BD", "Chakma (Bangladesh)" },
        { "ccp-IN", "Chakma (India)" },
        { "ff-Adlm", "Fula (Adlam)" },
        { "ff-Adlm-LR", "Fula (Adlam, Liberia)" },
        { "ff-Adlm-MR", "Fula (Adlam, Mauritania)" },
        { "ff-Adlm-BF", "Fula (Adlam, Burkina Faso)" },
        { "ff-Adlm-SL", "Fula (Adlam, Sierra Leone)" },
        { "ff-Adlm-SN", "Fula (Adlam, Senegal)" },
        { "ff-Adlm-NG", "Fula (Adlam, Nigeria)" },
        { "ff-Adlm-NE", "Fula (Adlam, Niger)" },
        { "ff-Adlm-CM", "Fula (Adlam, Cameroon)" },
        { "ff-Adlm-GM", "Fula (Adlam, Gambia)" },
        { "ff-Adlm-GH", "Fula (Adlam, Ghana)" },
        { "ff-Adlm-GN", "Fula (Adlam, Guinea)" },
        { "ff-Adlm-GW", "Fula (Adlam, Guinea-Bissau)" },
    };
}